#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import secrets
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import quote, urlparse


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.workflow_v3.minio_role_policy import (  # noqa: E402
    MINIO_ROLES,
    credential_fingerprint,
    parse_credential_fingerprints,
    role_policy_documents,
)


_DENIED_CODES = frozenset(
    {
        "AccessDenied",
        "AllAccessDisabled",
        "MethodNotAllowed",
        "Unauthorized",
    }
)
_PRECONDITION_CODES = frozenset(
    {"ConditionalRequestConflict", "PreconditionFailed", "ConditionNotMet"}
)
_SOURCE_BUCKETS = (
    "eduassets-input",
    "eduassets-mineru",
    "eduassets-minerupopo",
)


class MinioBootstrapError(RuntimeError):
    pass


def _env(name: str, *, fallback: str = "", required: bool = False) -> str:
    value = os.getenv(name, fallback).strip()
    if required and not value:
        raise MinioBootstrapError(f"{name} is required")
    return value


def _bool(value: str) -> bool:
    normalized = value.strip().lower()
    if normalized not in {"1", "true", "yes", "on", "0", "false", "no", "off"}:
        raise MinioBootstrapError("boolean value is invalid")
    return normalized in {"1", "true", "yes", "on"}


def _endpoint(value: str, *, secure: bool) -> tuple[str, bool, str]:
    raw = value.strip()
    if "://" not in raw:
        if not raw or "/" in raw or "@" in raw:
            raise MinioBootstrapError("MinIO endpoint must be host:port")
        scheme = "https" if secure else "http"
        return raw, secure, f"{scheme}://{raw}"
    parsed = urlparse(raw)
    if (
        parsed.scheme not in {"http", "https"}
        or not parsed.netloc
        or parsed.path not in {"", "/"}
        or parsed.params
        or parsed.query
        or parsed.fragment
        or parsed.username
        or parsed.password
    ):
        raise MinioBootstrapError("MinIO endpoint is unsafe")
    return parsed.netloc, parsed.scheme == "https", f"{parsed.scheme}://{parsed.netloc}"


def _safe_component(value: str, *, field: str) -> str:
    normalized = value.strip().strip("/")
    if (
        not normalized
        or "\\" in normalized
        or any(part in {"", ".", ".."} for part in normalized.split("/"))
    ):
        raise MinioBootstrapError(f"{field} is unsafe")
    return normalized


def _load_runtime_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    mode = stat.S_IMODE(path.stat().st_mode)
    if mode != 0o600:
        raise MinioBootstrapError(
            f"existing runtime env must have mode 0600, found {mode:04o}"
        )
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        name, separator, value = line.partition("=")
        if not separator or not name or any(character.isspace() for character in name):
            raise MinioBootstrapError("runtime env contains an invalid line")
        values[name] = value
    return values


def _role_credentials(
    existing: dict[str, str],
    *,
    principal_prefix: str,
) -> dict[str, tuple[str, str]]:
    credentials: dict[str, tuple[str, str]] = {}
    for role in MINIO_ROLES:
        prefix = f"WORKFLOW_V3_{role.upper()}_MINIO"
        access_key = existing.get(f"{prefix}_ACCESS_KEY", "").strip()
        secret_key = existing.get(f"{prefix}_SECRET_KEY", "").strip()
        if bool(access_key) != bool(secret_key):
            raise MinioBootstrapError(
                f"runtime env has an incomplete {role} credential pair"
            )
        credentials[role] = (
            access_key or f"{principal_prefix}-{role}",
            secret_key or secrets.token_urlsafe(36),
        )
    pairs = list(credentials.values())
    if len({access for access, _secret in pairs}) != len(MINIO_ROLES):
        raise MinioBootstrapError("role access keys must be distinct")
    if len({secret for _access, secret in pairs}) != len(MINIO_ROLES):
        raise MinioBootstrapError("role secret keys must be distinct")
    if len({credential_fingerprint(*pair) for pair in pairs}) != len(MINIO_ROLES):
        raise MinioBootstrapError("role credentials must be distinct")
    return credentials


def _runtime_env_text(
    *,
    endpoint: str,
    secure: bool,
    region: str,
    credentials: dict[str, tuple[str, str]],
) -> str:
    fingerprints = ",".join(
        f"{role}:{credential_fingerprint(*credentials[role])}"
        for role in MINIO_ROLES
    )
    lines = [
        "# Generated by workflow_v3_minio_admin.py; do not commit.",
        f"WORKFLOW_V3_MINIO_ENDPOINT={endpoint}",
        f"WORKFLOW_V3_MINIO_SECURE={'true' if secure else 'false'}",
        f"WORKFLOW_V3_MINIO_REGION={region}",
        f"WORKFLOW_V3_MINIO_CREDENTIAL_FINGERPRINTS={fingerprints}",
    ]
    for role in MINIO_ROLES:
        prefix = f"WORKFLOW_V3_{role.upper()}_MINIO"
        access_key, secret_key = credentials[role]
        lines.extend(
            [
                f"{prefix}_ACCESS_KEY={access_key}",
                f"{prefix}_SECRET_KEY={secret_key}",
            ]
        )
    return "\n".join(lines) + "\n"


def _write_runtime_env(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    descriptor, temporary = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
    )
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
        path.chmod(0o600)
    except Exception:
        try:
            os.close(descriptor)
        except OSError:
            pass
        Path(temporary).unlink(missing_ok=True)
        raise


def _redact(value: str, secrets_to_hide: tuple[str, ...]) -> str:
    result = value
    for secret in secrets_to_hide:
        if secret:
            result = result.replace(secret, "<redacted>")
    return result


def _mc_environment(
    *,
    admin_url: str,
    admin_access_key: str,
    admin_secret_key: str,
) -> dict[str, str]:
    result = dict(os.environ)
    result["MC_HOST_luceonv3"] = (
        f"{admin_url.split('://', 1)[0]}://"
        f"{quote(admin_access_key, safe='')}:{quote(admin_secret_key, safe='')}@"
        f"{admin_url.split('://', 1)[1]}"
    )
    return result


def _run_mc(
    mc_binary: str,
    arguments: list[str],
    *,
    environment: dict[str, str],
    secrets_to_hide: tuple[str, ...],
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        [mc_binary, *arguments],
        text=True,
        capture_output=True,
        env=environment,
        check=False,
        timeout=60,
    )
    if check and result.returncode != 0:
        detail = _redact(
            (result.stderr or result.stdout).strip()[-1000:],
            secrets_to_hide,
        )
        action = _redact(" ".join(arguments[:3]), secrets_to_hide)
        raise MinioBootstrapError(
            f"MinIO admin command failed for {action}: {detail}"
        )
    return result


def _bootstrap_principals(
    *,
    mc_binary: str,
    mc_environment: dict[str, str],
    policies: dict[str, dict],
    credentials: dict[str, tuple[str, str]],
    secrets_to_hide: tuple[str, ...],
) -> None:
    with tempfile.TemporaryDirectory(prefix="worker-v3-minio-policy-") as raw:
        root = Path(raw)
        for role in MINIO_ROLES:
            policy_name = f"luceon-worker-v3-{role}"
            policy_path = root / f"{role}.json"
            policy_path.write_text(
                json.dumps(policies[role], sort_keys=True, separators=(",", ":")),
                encoding="utf-8",
            )
            access_key, secret_key = credentials[role]
            info = _run_mc(
                mc_binary,
                ["admin", "user", "info", "luceonv3", access_key, "--json"],
                environment=mc_environment,
                secrets_to_hide=secrets_to_hide,
                check=False,
            )
            if info.returncode != 0:
                _run_mc(
                    mc_binary,
                    [
                        "admin",
                        "user",
                        "add",
                        "luceonv3",
                        access_key,
                        secret_key,
                    ],
                    environment=mc_environment,
                    secrets_to_hide=secrets_to_hide,
                )
            _run_mc(
                mc_binary,
                [
                    "admin",
                    "policy",
                    "create",
                    "luceonv3",
                    policy_name,
                    str(policy_path),
                ],
                environment=mc_environment,
                secrets_to_hide=secrets_to_hide,
            )
            _run_mc(
                mc_binary,
                [
                    "admin",
                    "policy",
                    "attach",
                    "luceonv3",
                    policy_name,
                    "--user",
                    access_key,
                ],
                environment=mc_environment,
                secrets_to_hide=secrets_to_hide,
            )


def _error_code(exc: Exception) -> str:
    return str(getattr(exc, "code", "") or getattr(exc, "status", "") or "")


def _expect_denied(name: str, operation) -> dict[str, str]:
    try:
        operation()
    except Exception as exc:
        code = _error_code(exc)
        if code in _DENIED_CODES:
            return {"name": name, "status": "passed", "observed": "denied"}
        raise MinioBootstrapError(
            f"{name} returned unexpected error code {code or type(exc).__name__}"
        ) from exc
    raise MinioBootstrapError(f"{name} unexpectedly succeeded")


def _read_bytes(client, bucket: str, object_name: str) -> bytes:
    response = client.get_object(bucket, object_name)
    try:
        return response.read()
    finally:
        response.close()
        response.release_conn()


def _conditional_put(
    client,
    bucket: str,
    object_name: str,
    payload: bytes,
) -> None:
    client._put_object(
        bucket,
        object_name,
        payload,
        {
            "Content-Type": "application/octet-stream",
            "If-None-Match": "*",
            "X-Amz-Meta-luceon-policy-probe": "true",
        },
    )


def _put_idempotent(client, bucket: str, object_name: str, payload: bytes) -> None:
    try:
        _conditional_put(client, bucket, object_name, payload)
    except Exception as exc:
        if _error_code(exc) not in _PRECONDITION_CODES:
            raise
        if _read_bytes(client, bucket, object_name) != payload:
            raise MinioBootstrapError(
                "existing policy probe object has conflicting bytes"
            ) from exc


def _expect_conditional_overwrite_rejected(
    name: str,
    client,
    bucket: str,
    object_name: str,
    original: bytes,
) -> dict[str, str]:
    try:
        _conditional_put(client, bucket, object_name, b"conflicting-overwrite")
    except Exception as exc:
        if _error_code(exc) not in _PRECONDITION_CODES:
            raise MinioBootstrapError(
                f"{name} returned unexpected error code "
                f"{_error_code(exc) or type(exc).__name__}"
            ) from exc
    else:
        raise MinioBootstrapError(f"{name} unexpectedly overwrote an object")
    if _read_bytes(client, bucket, object_name) != original:
        raise MinioBootstrapError(f"{name} did not preserve original bytes")
    return {
        "name": name,
        "status": "passed",
        "observed": "conditional_write_rejected",
    }


def _minio_clients(
    *,
    endpoint: str,
    secure: bool,
    region: str,
    credentials: dict[str, tuple[str, str]],
):
    from minio import Minio

    return {
        role: Minio(
            endpoint,
            access_key=credentials[role][0],
            secret_key=credentials[role][1],
            secure=secure,
            region=region,
        )
        for role in MINIO_ROLES
    }


def _verify_policy_matrix(
    *,
    clients,
    source_probe: tuple[str, str],
    candidate_bucket: str,
    candidate_prefix: str,
    formal_bucket: str,
    formal_prefix: str,
) -> list[dict[str, str]]:
    source_bucket, source_object = source_probe
    candidate_payload = b"worker-v3-producer-policy-probe-v1"
    candidate_digest = hashlib.sha256(candidate_payload).hexdigest()
    candidate_object = (
        f"{candidate_prefix}/_policy-probes/producer/"
        f"{candidate_digest}/object.bin"
    )
    formal_payload = b"worker-v3-projector-policy-probe-v1"
    formal_digest = hashlib.sha256(formal_payload).hexdigest()
    formal_object = (
        f"{formal_prefix}/_policy-probes/projector/"
        f"{formal_digest}/object.bin"
    )
    denied_candidate = f"{candidate_prefix}/_policy-probes/denied/object.bin"
    denied_formal = f"{formal_prefix}/_policy-probes/denied/object.bin"
    checks: list[dict[str, str]] = []

    _read_bytes(clients["producer"], source_bucket, source_object)
    checks.append(
        {"name": "producer_get_frozen_source", "status": "passed", "observed": "allowed"}
    )
    _put_idempotent(
        clients["producer"],
        candidate_bucket,
        candidate_object,
        candidate_payload,
    )
    checks.append(
        {"name": "producer_put_candidate", "status": "passed", "observed": "allowed"}
    )
    checks.append(
        _expect_conditional_overwrite_rejected(
            "producer_overwrite_candidate",
            clients["producer"],
            candidate_bucket,
            candidate_object,
            candidate_payload,
        )
    )

    for role in ("evaluator", "promoter"):
        _read_bytes(clients[role], candidate_bucket, candidate_object)
        checks.append(
            {
                "name": f"{role}_get_candidate",
                "status": "passed",
                "observed": "allowed",
            }
        )
        checks.append(
            _expect_denied(
                f"{role}_get_source",
                lambda role=role: _read_bytes(
                    clients[role],
                    source_bucket,
                    source_object,
                ),
            )
        )
        checks.append(
            _expect_denied(
                f"{role}_put_candidate",
                lambda role=role: clients[role].put_object(
                    candidate_bucket,
                    denied_candidate,
                    io.BytesIO(b"denied"),
                    6,
                ),
            )
        )

    _read_bytes(clients["projector"], candidate_bucket, candidate_object)
    checks.append(
        {"name": "projector_get_candidate", "status": "passed", "observed": "allowed"}
    )
    _put_idempotent(
        clients["projector"],
        formal_bucket,
        formal_object,
        formal_payload,
    )
    checks.append(
        {"name": "projector_put_formal", "status": "passed", "observed": "allowed"}
    )
    checks.append(
        _expect_conditional_overwrite_rejected(
            "projector_overwrite_formal",
            clients["projector"],
            formal_bucket,
            formal_object,
            formal_payload,
        )
    )
    checks.append(
        _expect_denied(
            "projector_get_source",
            lambda: _read_bytes(
                clients["projector"],
                source_bucket,
                source_object,
            ),
        )
    )
    checks.append(
        _expect_denied(
            "projector_put_candidate",
            lambda: clients["projector"].put_object(
                candidate_bucket,
                denied_candidate,
                io.BytesIO(b"denied"),
                6,
            ),
        )
    )
    checks.append(
        _expect_denied(
            "producer_put_formal",
            lambda: clients["producer"].put_object(
                formal_bucket,
                denied_formal,
                io.BytesIO(b"denied"),
                6,
            ),
        )
    )
    for role, bucket, object_name in (
        ("producer", candidate_bucket, candidate_object),
        ("evaluator", candidate_bucket, candidate_object),
        ("promoter", candidate_bucket, candidate_object),
        ("projector", formal_bucket, formal_object),
    ):
        checks.append(
            _expect_denied(
                f"{role}_delete_object",
                lambda role=role, bucket=bucket, object_name=object_name: clients[
                    role
                ].remove_object(bucket, object_name),
            )
        )
    return checks


def _versioning_status(
    *,
    mc_binary: str,
    mc_environment: dict[str, str],
    bucket: str,
    secrets_to_hide: tuple[str, ...],
) -> str:
    result = _run_mc(
        mc_binary,
        ["version", "info", f"luceonv3/{bucket}", "--json"],
        environment=mc_environment,
        secrets_to_hide=secrets_to_hide,
    )
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise MinioBootstrapError("mc version info did not return JSON") from exc
    return _parse_versioning_status(payload)


def _parse_versioning_status(payload: object) -> str:
    if not isinstance(payload, dict):
        raise MinioBootstrapError("mc version info returned an invalid payload")
    versioning = payload.get("versioning")
    if isinstance(versioning, dict):
        raw_status = versioning.get("status")
    elif isinstance(versioning, str):
        raw_status = versioning
    else:
        raw_status = payload.get("versioningStatus")
    status = str(raw_status or "").strip().lower()
    if status == "enabled":
        return "enabled"
    if status == "suspended":
        return "suspended"
    return "disabled" if not status or status == "disabled" else status


def _object_lock_status(
    *,
    mc_binary: str,
    mc_environment: dict[str, str],
    bucket: str,
    secrets_to_hide: tuple[str, ...],
) -> str:
    result = _run_mc(
        mc_binary,
        ["retention", "info", "--default", f"luceonv3/{bucket}", "--json"],
        environment=mc_environment,
        secrets_to_hide=secrets_to_hide,
        check=False,
    )
    if result.returncode != 0:
        return "not_configured_or_unsupported"
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise MinioBootstrapError("mc retention info did not return JSON") from exc
    mode = str(
        payload.get("mode")
        or payload.get("retentionMode")
        or payload.get("status")
        or ""
    ).strip()
    return mode.lower() if mode else "configured"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Bootstrap and verify distinct least-privilege MinIO identities "
            "for the four ordinary Worker V3 roles."
        )
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true")
    mode.add_argument("--verify-only", action="store_true")
    parser.add_argument(
        "--runtime-env",
        type=Path,
        default=Path("runtime/worker-v3/minio-roles.env"),
    )
    parser.add_argument("--mc", default=os.getenv("MC_BINARY", "mc"))
    parser.add_argument(
        "--principal-prefix",
        default="luceon-worker-v3",
    )
    parser.add_argument(
        "--source-buckets",
        default=",".join(_SOURCE_BUCKETS),
    )
    parser.add_argument("--source-probe", default="")
    parser.add_argument("--require-versioning", action="store_true")
    parser.add_argument("--require-object-lock", action="store_true")
    args = parser.parse_args(argv)

    try:
        source_buckets = tuple(
            _safe_component(value, field="source bucket")
            for value in args.source_buckets.split(",")
            if value.strip()
        )
        candidate_bucket = _safe_component(
            _env(
                "WORKFLOW_V3_CANDIDATE_BUCKET",
                fallback="worker-v3-candidates",
            ),
            field="candidate bucket",
        )
        candidate_prefix = _safe_component(
            _env(
                "WORKFLOW_V3_CANDIDATE_PREFIX",
                fallback="v3/candidates",
            ),
            field="candidate prefix",
        )
        formal_bucket = _safe_component(
            _env(
                "WORKFLOW_V3_FORMAL_BUCKET",
                fallback="eduassets-elegantbook",
            ),
            field="formal bucket",
        )
        formal_prefix = _safe_component(
            _env(
                "WORKFLOW_V3_FORMAL_PREFIX",
                fallback="elegantbook/v3",
            ),
            field="formal prefix",
        )
        if not source_buckets:
            raise MinioBootstrapError("at least one source bucket is required")
        policies = role_policy_documents(
            candidate_bucket=candidate_bucket,
            candidate_prefix=candidate_prefix,
            formal_bucket=formal_bucket,
            formal_prefix=formal_prefix,
            source_buckets=source_buckets,
        )
        if args.dry_run:
            print(
                json.dumps(
                    {
                        "ok": True,
                        "mode": "dry-run",
                        "mutated": False,
                        "roles": list(MINIO_ROLES),
                        "runtime_env": str(args.runtime_env),
                        "policy_sha256": {
                            role: hashlib.sha256(
                                json.dumps(
                                    policies[role],
                                    sort_keys=True,
                                    separators=(",", ":"),
                                ).encode("utf-8")
                            ).hexdigest()
                            for role in MINIO_ROLES
                        },
                    },
                    sort_keys=True,
                )
            )
            return 0

        existing = _load_runtime_env(args.runtime_env)
        if args.verify_only and not existing:
            raise MinioBootstrapError(
                "--verify-only requires an existing 0600 runtime env"
            )
        credentials = _role_credentials(
            existing,
            principal_prefix=args.principal_prefix,
        )
        fingerprints = ",".join(
            f"{role}:{credential_fingerprint(*credentials[role])}"
            for role in MINIO_ROLES
        )
        parse_credential_fingerprints(fingerprints)
        admin_endpoint = _env(
            "MINIO_ADMIN_ENDPOINT",
            fallback=_env(
                "MINIO_INTERNAL_ENDPOINT",
                fallback=_env("MINIO_ENDPOINT"),
            ),
            required=True,
        )
        admin_access_key = _env(
            "MINIO_ADMIN_ACCESS_KEY",
            fallback=_env("MINIO_ACCESS_KEY"),
            required=True,
        )
        admin_secret_key = _env(
            "MINIO_ADMIN_SECRET_KEY",
            fallback=_env("MINIO_SECRET_KEY"),
            required=True,
        )
        secure_default = _bool(
            _env("MINIO_ADMIN_SECURE", fallback=_env("MINIO_SECURE", fallback="false"))
        )
        endpoint, secure, admin_url = _endpoint(
            admin_endpoint,
            secure=secure_default,
        )
        region = _env("WORKFLOW_V3_MINIO_REGION", fallback="us-east-1")
        secrets_to_hide = (
            admin_access_key,
            admin_secret_key,
            *(value for pair in credentials.values() for value in pair),
        )
        mc_binary = shutil.which(args.mc)
        if not mc_binary:
            raise MinioBootstrapError(f"MinIO client binary not found: {args.mc}")
        mc_environment = _mc_environment(
            admin_url=admin_url,
            admin_access_key=admin_access_key,
            admin_secret_key=admin_secret_key,
        )
        if not args.verify_only:
            _write_runtime_env(
                args.runtime_env,
                _runtime_env_text(
                    endpoint=endpoint,
                    secure=secure,
                    region=region,
                    credentials=credentials,
                ),
            )
            _bootstrap_principals(
                mc_binary=mc_binary,
                mc_environment=mc_environment,
                policies=policies,
                credentials=credentials,
                secrets_to_hide=secrets_to_hide,
            )
        source_bucket, separator, source_object = args.source_probe.partition("/")
        if (
            not separator
            or source_bucket not in source_buckets
            or not _safe_component(source_object, field="source probe object")
        ):
            raise MinioBootstrapError(
                "--source-probe must name an existing object in a configured "
                "frozen source bucket"
            )
        versioning = {
            bucket: _versioning_status(
                mc_binary=mc_binary,
                mc_environment=mc_environment,
                bucket=bucket,
                secrets_to_hide=secrets_to_hide,
            )
            for bucket in (candidate_bucket, formal_bucket)
        }
        if args.require_versioning and any(
            status != "enabled" for status in versioning.values()
        ):
            raise MinioBootstrapError(
                "candidate and formal bucket versioning must both be enabled"
            )
        object_lock = {
            bucket: _object_lock_status(
                mc_binary=mc_binary,
                mc_environment=mc_environment,
                bucket=bucket,
                secrets_to_hide=secrets_to_hide,
            )
            for bucket in (candidate_bucket, formal_bucket)
        }
        if args.require_object_lock and any(
            status in {"not_configured_or_unsupported", "disabled"}
            for status in object_lock.values()
        ):
            raise MinioBootstrapError(
                "candidate and formal bucket object lock must both be configured"
            )
        checks = _verify_policy_matrix(
            clients=_minio_clients(
                endpoint=endpoint,
                secure=secure,
                region=region,
                credentials=credentials,
            ),
            source_probe=(source_bucket, source_object),
            candidate_bucket=candidate_bucket,
            candidate_prefix=candidate_prefix,
            formal_bucket=formal_bucket,
            formal_prefix=formal_prefix,
        )
        print(
            json.dumps(
                {
                    "ok": True,
                    "mode": "verify-only" if args.verify_only else "bootstrap",
                    "runtime_env": str(args.runtime_env),
                    "runtime_env_mode": (
                        f"{stat.S_IMODE(args.runtime_env.stat().st_mode):04o}"
                    ),
                    "roles": list(MINIO_ROLES),
                    "versioning": versioning,
                    "object_lock": object_lock,
                    "checks": checks,
                },
                sort_keys=True,
            )
        )
        return 0
    except Exception as exc:
        print(
            json.dumps(
                {
                    "ok": False,
                    "error": (
                        str(exc)
                        if isinstance(exc, MinioBootstrapError)
                        else type(exc).__name__
                    ),
                },
                sort_keys=True,
            ),
            file=sys.stderr,
        )
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
