/**
 * 全局 Mock 数据
 * 从各页面组件中集中迁移的静态数据，统一作为全局 Store 的初始状态
 */

import type {
  Material,
  ProcessTask,
  Task,
  Product,
  FlexibleTag,
  AiRule,
  AiRuleSettings,
  AssetDetail,
  AiConfig,
  MinerUConfig,
} from './types';

// ==================== 原始资料 ====================

/** 原始资料列表（初始数据） */
export const initialMaterials: Material[] = [
  {
    id: 1,
    title: '2024年高考数学真题（全国卷I）',
    type: 'PDF',
    size: '12.5 MB',
    sizeBytes: 13107200,
    uploadTime: '2小时前',
    uploadTimestamp: Date.now() - 2 * 60 * 60 * 1000,
    status: 'processing',
    mineruStatus: 'completed',
    aiStatus: 'analyzing',
    tags: ['数学', '高三', '高考', '全国卷', '真题'],
    metadata: {
      subject: '数学',
      grade: '高三',
      type: '真题',
      standard: '新课标2022',
      region: '全国',
      year: '2024',
    },
    uploader: '张明',
  },
  {
    id: 2,
    title: '初中英语语法专项练习',
    type: 'DOCX',
    size: '3.2 MB',
    sizeBytes: 3355443,
    uploadTime: '5小时前',
    uploadTimestamp: Date.now() - 5 * 60 * 60 * 1000,
    status: 'completed',
    mineruStatus: 'completed',
    aiStatus: 'analyzed',
    tags: ['英语', '初中', '语法', '专项练习'],
    metadata: {
      subject: '英语',
      grade: '初中',
      type: '练习册',
      standard: '义务教育课标',
      region: '通用',
    },
    uploader: '李华',
  },
  {
    id: 3,
    title: '小学数学应用题集（人教版）',
    type: 'PDF',
    size: '8.7 MB',
    sizeBytes: 9122611,
    uploadTime: '1天前',
    uploadTimestamp: Date.now() - 24 * 60 * 60 * 1000,
    status: 'completed',
    mineruStatus: 'completed',
    aiStatus: 'analyzed',
    tags: ['数学', '小学', '应用题', '人教版'],
    metadata: {
      subject: '数学',
      grade: '小学',
      type: '练习册',
      standard: '人教版',
      region: '通用',
    },
    uploader: '王芳',
  },
  {
    id: 4,
    title: '高中物理实验指导手册',
    type: 'PPT',
    size: '25.3 MB',
    sizeBytes: 26527334,
    uploadTime: '1天前',
    uploadTimestamp: Date.now() - 25 * 60 * 60 * 1000,
    status: 'completed',
    mineruStatus: 'completed',
    aiStatus: 'analyzed',
    tags: ['物理', '高中', '实验', '指导手册'],
    metadata: {
      subject: '物理',
      grade: '高中',
      type: '教学资料',
      standard: '新课标2022',
      region: '通用',
    },
    uploader: '刘洋',
  },
  {
    id: 5,
    title: '初中历史知识点总结',
    type: 'PDF',
    size: '5.1 MB',
    sizeBytes: 5348147,
    uploadTime: '2天前',
    uploadTimestamp: Date.now() - 48 * 60 * 60 * 1000,
    status: 'pending',
    mineruStatus: 'pending',
    aiStatus: 'pending',
    tags: [],
    metadata: {},
    uploader: '陈刚',
  },
  {
    id: 6,
    title: '高考英语作文范文集',
    type: 'DOCX',
    size: '1.8 MB',
    sizeBytes: 1887437,
    uploadTime: '2天前',
    uploadTimestamp: Date.now() - 49 * 60 * 60 * 1000,
    status: 'completed',
    mineruStatus: 'completed',
    aiStatus: 'analyzed',
    tags: ['英语', '高三', '作文', '范文'],
    metadata: {
      subject: '英语',
      grade: '高三',
      type: '教学资料',
      standard: '新课标2022',
      region: '通用',
    },
    uploader: '赵敏',
  },
  {
    id: 7,
    title: '初中化学实验报告模板',
    type: 'DOCX',
    size: '2.4 MB',
    sizeBytes: 2516582,
    uploadTime: '3天前',
    uploadTimestamp: Date.now() - 72 * 60 * 60 * 1000,
    status: 'failed',
    mineruStatus: 'failed',
    aiStatus: 'pending',
    tags: ['化学', '初中', '实验'],
    metadata: { subject: '化学', grade: '初中', type: '教学资料' },
    uploader: '孙磊',
  },
  {
    id: 8,
    title: '小学语文阅读理解专项',
    type: 'PDF',
    size: '6.9 MB',
    sizeBytes: 7235174,
    uploadTime: '3天前',
    uploadTimestamp: Date.now() - 73 * 60 * 60 * 1000,
    status: 'reviewing',
    mineruStatus: 'completed',
    aiStatus: 'analyzed',
    tags: ['语文', '小学', '阅读理解'],
    metadata: {
      subject: '语文',
      grade: '小学',
      type: '练习册',
      standard: '人教版',
      region: '通用',
    },
    uploader: '周静',
  },
];

// ==================== 处理任务 ====================

/** 处理中心任务列表（初始数据） */
export const initialProcessTasks: ProcessTask[] = [
  {
    id: 1,
    name: 'MinerU解析：2024年高考数学真题',
    type: 'rawcode生成',
    status: 'processing',
    stage: 'MinerU解析中',
    progress: 75,
    input: '2024年高考数学真题（全国卷I）.pdf',
    output: 'markdown + latex + images',
    assignee: '张明',
    startTime: '2026-04-02 14:00',
    estimatedTime: '5分钟',
    logs: [
      { time: '14:35:22', level: 'info', msg: '正在解析第9页/共12页...' },
      { time: '14:30:15', level: 'success', msg: '图片提取完成，共识别 8 张图片' },
      { time: '14:25:08', level: 'info', msg: 'LaTeX 公式识别中，已识别 23 个公式' },
      { time: '14:15:00', level: 'info', msg: 'MinerU 解析任务启动' },
    ],
  },
  {
    id: 2,
    name: 'AI清洗：初中英语语法练习',
    type: 'cleancode生成',
    status: 'reviewing',
    stage: '待人工审核',
    progress: 100,
    input: 'rawcode_english_grammar.md',
    output: 'cleancode_english_grammar.md',
    assignee: '李华',
    startTime: '2026-04-02 13:30',
    estimatedTime: '已完成',
    reviewNote: '请重点检查语法术语的标准化',
    diffStats: { added: 42, removed: 18, changed: 7 },
    logs: [
      { time: '14:20:00', level: 'warning', msg: '等待审核人员确认' },
      { time: '14:00:00', level: 'success', msg: 'AI清洗完成，等待审核' },
      { time: '13:45:00', level: 'info', msg: '格式标准化处理中' },
    ],
  },
  {
    id: 3,
    name: '题库生成：高中物理实验题',
    type: '成品生成',
    status: 'processing',
    stage: '结构化数据生成',
    progress: 90,
    input: 'cleancode_physics_exp.md',
    output: '题库JSON',
    assignee: '王芳',
    startTime: '2026-04-02 13:00',
    estimatedTime: '2分钟',
    logs: [
      { time: '14:30:00', level: 'info', msg: '题目难度标注中，已处理 45/50 题' },
      { time: '14:15:00', level: 'success', msg: '知识点关联完成' },
      { time: '14:00:00', level: 'success', msg: '题型分类完成' },
    ],
  },
  {
    id: 4,
    name: 'OCR识别：小学数学试卷扫描件',
    type: 'rawcode生成',
    status: 'pending',
    stage: '等待开始',
    progress: 0,
    input: 'scan_math_paper_001.jpg',
    output: 'markdown',
    assignee: '刘洋',
    startTime: '待分配',
    estimatedTime: '10分钟',
    logs: [],
  },
  {
    id: 5,
    name: '格式转换：高中化学方程式整理',
    type: 'cleancode生成',
    status: 'failed',
    stage: 'LaTeX解析失败',
    progress: 45,
    input: 'rawcode_chemistry.md',
    output: '-',
    assignee: '陈刚',
    startTime: '2026-04-02 12:00',
    estimatedTime: '-',
    error: 'LaTeX 语法错误：第127行缺少闭合括号 `}`',
    logs: [
      { time: '12:45:00', level: 'error', msg: '任务失败：LaTeX 解析错误 at line 127' },
      { time: '12:30:00', level: 'warning', msg: '检测到多处语法错误，尝试自动修复' },
      { time: '12:15:00', level: 'info', msg: '开始解析化学方程式' },
    ],
  },
  {
    id: 6,
    name: '讲义生成：初中历史知识点总结',
    type: '成品生成',
    status: 'completed',
    stage: '已完成',
    progress: 100,
    input: 'cleancode_history.md',
    output: '讲义PDF',
    assignee: '赵敏',
    startTime: '2026-04-02 11:00',
    estimatedTime: '已完成',
    logs: [
      { time: '13:00:00', level: 'success', msg: '任务完成，输出文件已保存' },
      { time: '12:45:00', level: 'success', msg: 'PDF 生成完成，共 24 页' },
      { time: '12:00:00', level: 'info', msg: '排版处理中' },
    ],
  },
];

// ==================== 任务中心 ====================

/** 任务中心任务列表（初始数据） */
export const initialTasks: Task[] = [
  {
    id: 'TASK-2024-001',
    name: 'MinerU解析：2024年高考数学真题',
    type: 'MinerU解析',
    status: 'processing',
    priority: 'high',
    createdAt: '2026-04-02 14:00',
    updatedAt: '2026-04-02 14:35',
    assignee: '张明',
    input: '2024年高考数学真题（全国卷I）.pdf',
    output: 'rawcode/',
    progress: 75,
    logs: [
      { time: '14:35:22', level: 'info', msg: '正在解析第9页/共12页...' },
      { time: '14:30:15', level: 'success', msg: '图片提取完成，共识别 8 张图片' },
      { time: '14:15:00', level: 'info', msg: 'MinerU 解析任务启动' },
    ],
  },
  {
    id: 'TASK-2024-002',
    name: 'AI清洗：初中英语语法练习',
    type: 'AI清洗',
    status: 'reviewing',
    priority: 'medium',
    createdAt: '2026-04-02 13:30',
    updatedAt: '2026-04-02 14:20',
    assignee: '李华',
    input: 'rawcode_english_grammar.md',
    output: 'cleancode_english_grammar.md',
    progress: 100,
    reviewNote: '请重点检查语法术语的标准化',
    logs: [
      { time: '14:20:00', level: 'warning', msg: '等待审核人员确认' },
      { time: '14:00:00', level: 'success', msg: 'AI清洗完成，等待审核' },
    ],
  },
  {
    id: 'TASK-2024-003',
    name: '题库生成：高中物理实验题',
    type: '成品生成',
    status: 'processing',
    priority: 'high',
    createdAt: '2026-04-02 13:00',
    updatedAt: '2026-04-02 14:30',
    assignee: '王芳',
    input: 'cleancode_physics_exp.md',
    output: 'product_physics_bank.json',
    progress: 90,
    logs: [
      { time: '14:30:00', level: 'info', msg: '题目难度标注中，已处理 45/50 题' },
      { time: '14:15:00', level: 'success', msg: '知识点关联完成' },
    ],
  },
  {
    id: 'TASK-2024-004',
    name: 'OCR识别：小学数学试卷扫描件',
    type: 'OCR识别',
    status: 'pending',
    priority: 'low',
    createdAt: '2026-04-02 12:45',
    updatedAt: '2026-04-02 12:45',
    assignee: '刘洋',
    input: 'scan_math_paper_001.jpg',
    output: '-',
    progress: 0,
    logs: [],
  },
  {
    id: 'TASK-2024-005',
    name: '格式转换：高中化学方程式整理',
    type: '格式转换',
    status: 'failed',
    priority: 'medium',
    createdAt: '2026-04-02 12:00',
    updatedAt: '2026-04-02 12:45',
    assignee: '陈刚',
    input: 'rawcode_chemistry.md',
    output: '-',
    progress: 45,
    error: 'LaTeX 语法错误：第127行缺少闭合括号 `}`',
    logs: [
      { time: '12:45:00', level: 'error', msg: '任务失败：LaTeX 解析错误 at line 127' },
      { time: '12:30:00', level: 'warning', msg: '检测到多处语法错误，尝试自动修复' },
    ],
  },
  {
    id: 'TASK-2024-006',
    name: '讲义生成：初中历史知识点总结',
    type: '成品生成',
    status: 'completed',
    priority: 'medium',
    createdAt: '2026-04-02 11:00',
    updatedAt: '2026-04-02 13:00',
    assignee: '赵敏',
    input: 'cleancode_history.md',
    output: 'product_history_notes.pdf',
    progress: 100,
    logs: [
      { time: '13:00:00', level: 'success', msg: '任务完成，输出文件已保存' },
      { time: '12:45:00', level: 'success', msg: 'PDF 生成完成，共 24 页' },
    ],
  },
];

// ==================== 成品库 ====================

/** 成品列表（初始数据） */
export const initialProducts: Product[] = [
  {
    id: 1,
    title: '初中数学几何专题题库',
    type: '题库',
    description: '覆盖平面几何、立体几何等核心知识点，适合初中全学段使用',
    items: '320题',
    useCount: 156,
    rating: 4.8,
    status: 'completed',
    tags: ['数学', '初中', '几何', '专题'],
    metadata: { subject: '数学', grade: '初中', difficulty: '中等', standard: '义务教育课标' },
    source: 'cleancode_math_geometry.md',
    createdAt: '2026-03-28',
    lineage: ['小学数学应用题集（人教版）', 'rawcode_math_geometry.md', 'cleancode_math_geometry.md'],
    color: 'blue',
  },
  {
    id: 2,
    title: '高中英语阅读理解练习册',
    type: '练习册',
    description: '精选50篇高质量英语阅读材料，涵盖科技、文化、社会等多个话题',
    items: '50篇',
    useCount: 89,
    rating: 4.6,
    status: 'completed',
    tags: ['英语', '高中', '阅读理解', '练习册'],
    metadata: { subject: '英语', grade: '高中', difficulty: '中高', standard: '新课标2022' },
    source: 'cleancode_english_reading.md',
    createdAt: '2026-03-27',
    lineage: ['初中英语语法专项练习', 'rawcode_english_reading.md', 'cleancode_english_reading.md'],
    color: 'green',
  },
  {
    id: 3,
    title: '小学语文期末复习卷',
    type: '试卷',
    description: '针对小学语文期末考试的综合复习试卷，10套完整试题',
    items: '10套',
    useCount: 234,
    rating: 4.9,
    status: 'completed',
    tags: ['语文', '小学', '期末', '试卷'],
    metadata: { subject: '语文', grade: '小学', difficulty: '基础', standard: '部编版' },
    source: 'cleancode_chinese_final.md',
    createdAt: '2026-03-26',
    lineage: ['小学语文阅读理解专项', 'rawcode_chinese_final.md', 'cleancode_chinese_final.md'],
    color: 'purple',
  },
  {
    id: 4,
    title: '高考物理力学知识点讲义',
    type: '讲义',
    description: '系统梳理高中物理力学部分知识点，配有详细例题和解析',
    items: '15章节',
    useCount: 67,
    rating: 4.7,
    status: 'completed',
    tags: ['物理', '高三', '力学', '讲义'],
    metadata: { subject: '物理', grade: '高三', difficulty: '难', standard: '新课标2022' },
    source: 'cleancode_physics_mechanics.md',
    createdAt: '2026-03-25',
    lineage: ['高中物理实验指导手册', 'rawcode_physics_mechanics.md', 'cleancode_physics_mechanics.md'],
    color: 'orange',
  },
  {
    id: 5,
    title: '初中化学实验操作课程包',
    type: '课程包',
    description: '包含20个化学实验的操作指南、注意事项和配套练习',
    items: '20实验',
    useCount: 45,
    rating: 4.5,
    status: 'reviewing',
    tags: ['化学', '初中', '实验', '课程包'],
    metadata: { subject: '化学', grade: '初中', difficulty: '中等', standard: '义务教育课标' },
    source: 'cleancode_chemistry_exp.md',
    createdAt: '2026-03-24',
    lineage: ['初中化学实验报告模板', 'rawcode_chemistry_exp.md', 'cleancode_chemistry_exp.md'],
    color: 'yellow',
  },
  {
    id: 6,
    title: '高中历史古代史专题题库',
    type: '题库',
    description: '中国古代史核心考点题库，包含选择题、材料题等多种题型',
    items: '180题',
    useCount: 92,
    rating: 4.8,
    status: 'completed',
    tags: ['历史', '高中', '古代史', '专题'],
    metadata: { subject: '历史', grade: '高中', difficulty: '中等', standard: '新课标2022' },
    source: 'cleancode_history_ancient.md',
    createdAt: '2026-03-23',
    lineage: ['初中历史知识点总结', 'rawcode_history_ancient.md', 'cleancode_history_ancient.md'],
    color: 'indigo',
  },
];

// ==================== 标签 ====================

/** 灵活标签（初始数据） */
export const initialFlexibleTags: FlexibleTag[] = [
  { id: 1, name: '新课标2022', count: 1285, category: '课程标准', color: 'blue' },
  { id: 2, name: '数学', count: 2341, category: '学科', color: 'purple' },
  { id: 3, name: '高考', count: 892, category: '考试', color: 'red' },
  { id: 4, name: '初中', count: 1654, category: '学段', color: 'green' },
  { id: 5, name: '阅读理解', count: 567, category: '题型', color: 'orange' },
  { id: 6, name: '人教版', count: 1432, category: '教材版本', color: 'indigo' },
  { id: 7, name: '几何', count: 734, category: '知识点', color: 'pink' },
  { id: 8, name: '语法', count: 623, category: '知识点', color: 'yellow' },
  { id: 9, name: 'G3', count: 445, category: '年级', color: 'teal' },
  { id: 10, name: '专项练习', count: 821, category: '资料类型', color: 'cyan' },
  { id: 11, name: '中考', count: 678, category: '考试', color: 'red' },
  { id: 12, name: '实验', count: 389, category: '内容类型', color: 'lime' },
];

// ==================== AI 规则 ====================

/** AI 自动标注规则（初始数据） */
export const initialAiRules: AiRule[] = [
  {
    id: 1,
    name: '自动识别学科',
    enabled: true,
    condition: '文件内容包含学科关键词',
    action: '自动添加学科标签',
    priority: 1,
    executedCount: 2341,
    successRate: 96,
  },
  {
    id: 2,
    name: '课程标准识别',
    enabled: true,
    condition: '标题或内容包含"新课标"、"人教版"等',
    action: '自动添加课程标准标签',
    priority: 2,
    executedCount: 1854,
    successRate: 94,
  },
  {
    id: 3,
    name: '考试类型识别',
    enabled: true,
    condition: '标题包含"高考"、"中考"、"真题"',
    action: '自动添加考试类型标签',
    priority: 3,
    executedCount: 1432,
    successRate: 98,
  },
  {
    id: 4,
    name: '年级智能判断',
    enabled: true,
    condition: 'AI分析内容难度和知识点',
    action: '自动赋值年级字段',
    priority: 4,
    executedCount: 2156,
    successRate: 91,
  },
  {
    id: 5,
    name: '资料类型分类',
    enabled: false,
    condition: '根据文件结构和内容特征',
    action: '自动分类为试卷、练习册、讲义等',
    priority: 5,
    executedCount: 892,
    successRate: 87,
  },
];

/** AI 规则执行设置（初始数据） */
export const initialAiRuleSettings: AiRuleSettings = {
  autoOnUpload: true,
  parallelExecution: true,
  requireManualReview: false,
  lowConfidenceAlert: true,
  confidenceThreshold: 85,
};

// ==================== AI 识别配置 ====================

/** AI 识别配置（默认值） */
export const initialAiConfig: AiConfig = {
  apiEndpoint: 'https://api.moonshot.cn/v1/chat/completions',
  apiKey: '',
  model: 'moonshot-v1-32k',
  timeout: 300, // 默认 5 分钟，适应大文本识别需求
  prompts: {
    title: '根据以下教育资料的内容，生成一个简洁准确的中文资料名称。要求：包含学科、年级、内容类型等关键信息，长度不超过30字。',
    subject: '分析以下教育资料的内容，识别其所属学科。返回值仅限：数学、语文、英语、物理、化学、生物、历史、地理、政治、其他。',
    grade: '根据以下教育资料的难度和知识点范围，判断其适用的学段/年级。返回值格式：小学/初中/高中/高三。',
    materialType: '判断以下教育资料的类型分类。可选值：真题、练习册、试卷、教学资料、讲义、课件、题库、其他。',
    tags: '从以下教育资料的 Markdown 内容中提取 3~8 个关键标签，包含学科、年级、考试类型、教材版本、知识点等维度。以逗号分隔的纯文本形式返回。',
    summary: '用 2-3 句话概括以下教育资料的核心内容和适用场景，用于在列表中快速了解资料概况。',
  },
};

/** MinerU API 配置（默认值） */
export const initialMinerUConfig: MinerUConfig = {
  apiMode: 'precise',
  apiEndpoint: 'https://mineru.net/api/v4/extract/task',
  apiKey: '',  // 请在系统设置页面配置 MinerU API Key，或通过环境变量注入
  timeout: 1200,
  modelVersion: 'vlm',
  enableOcr: false,
  enableFormula: true,
  enableTable: true,
  language: 'ch',
};

// ==================== 资产详情 ====================

/** 资产详情（初始数据） */
export const initialAssetDetails: Record<number, AssetDetail> = {
  1: {
    id: 1,
    title: '2024年高考数学真题（全国卷I）',
    status: 'processing',
    assetId: 'AST-20240401-001',
    permission: 'production',
    tags: ['数学', '高三', '高考', '全国卷', '真题', '2024', '新课标'],
    metadata: {
      subject: '数学',
      grade: '高三',
      standard: '新课标2022',
      region: '全国',
      format: 'PDF',
      size: '12.5 MB',
      pages: 12,
      uploadTime: '2026-04-01 14:23',
      uploader: '张明',
      language: '中文',
      type: '真题',
      year: '2024',
    },
    lineage: [
      { stage: '原始资料', label: 'PDF 文档', color: 'blue', status: 'completed', file: 'math_gaokao_2024_I.pdf', size: '12.5 MB' },
      { stage: 'Rawcode', label: 'MinerU 输出', color: 'orange', status: 'processing', file: 'math_gaokao_2024_I.md', size: '2.1 MB' },
      { stage: 'Cleancode', label: '待生成', color: 'green', status: 'pending', file: null, size: null },
      { stage: '成品', label: '待生成', color: 'purple', status: 'pending', file: null, size: null },
    ],
    history: [
      { id: 1, action: '启动 MinerU 解析', time: '10分钟前', operator: '张明', type: 'system', note: '解析进度: 75% (9/12 页已完成)', status: 'processing' },
      { id: 2, action: '元数据自动抽取完成', time: '2小时前', operator: '系统', type: 'ai', note: '识别到：数学、高三、高考、全国卷、新课标2022', status: 'completed' },
      { id: 3, action: 'AI自动打标签', time: '2小时前', operator: 'AI引擎', type: 'ai', note: '自动添加标签：数学、高三、高考、全国卷、真题、2024、新课标', status: 'completed' },
      { id: 4, action: '文件上传完成', time: '2小时前', operator: '张明', type: 'user', note: '原始文件 math_gaokao_2024_I.pdf 上传成功', status: 'completed' },
    ],
    versions: [{ version: 'v1.0', status: 'current', time: '2026-04-01 14:23', operator: '张明', note: '初始上传版本' }],
    relatedAssets: [
      { id: 2, title: '初中英语语法专项练习', type: 'DOCX', status: 'completed' },
      { id: 3, title: '小学数学应用题集（人教版）', type: 'PDF', status: 'completed' },
      { id: 4, title: '高中物理实验指导手册', type: 'PPT', status: 'completed' },
    ],
  },
  2: {
    id: 2,
    title: '初中英语语法专项练习',
    status: 'completed',
    assetId: 'AST-20240401-002',
    permission: 'production',
    tags: ['英语', '初中', '语法', '专项练习'],
    metadata: {
      subject: '英语',
      grade: '初中',
      standard: '义务教育课标',
      region: '通用',
      format: 'DOCX',
      size: '3.2 MB',
      pages: 28,
      uploadTime: '2026-04-01 11:15',
      uploader: '李华',
      language: '中文',
      type: '练习册',
    },
    lineage: [
      { stage: '原始资料', label: 'Word 文档', color: 'blue', status: 'completed', file: 'english_grammar.docx', size: '3.2 MB' },
      { stage: 'Rawcode', label: 'MinerU 输出', color: 'orange', status: 'completed', file: 'english_grammar_raw.md', size: '740 KB' },
      { stage: 'Cleancode', label: 'AI清洗完成', color: 'green', status: 'completed', file: 'english_grammar_clean.md', size: '690 KB' },
      { stage: '成品', label: '可用', color: 'purple', status: 'completed', file: 'english_grammar_bank.json', size: '410 KB' },
    ],
    history: [
      { id: 1, action: '任务完成', time: '5小时前', operator: '系统', type: 'system', status: 'completed' },
      { id: 2, action: 'AI自动打标签', time: '5小时前', operator: 'AI引擎', type: 'ai', status: 'completed' },
      { id: 3, action: '文件上传完成', time: '5小时前', operator: '李华', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.0', status: 'current', time: '2026-04-01 11:15', operator: '李华', note: '初始上传版本' }],
    relatedAssets: [
      { id: 6, title: '高考英语作文范文集', type: 'DOCX', status: 'completed' },
      { id: 7, title: '初中化学实验报告模板', type: 'DOCX', status: 'failed' },
      { id: 8, title: '小学语文阅读理解专项', type: 'PDF', status: 'reviewing' },
    ],
  },
  3: {
    id: 3,
    title: '小学数学应用题集（人教版）',
    status: 'completed',
    assetId: 'AST-20240401-003',
    permission: 'production',
    tags: ['数学', '小学', '应用题', '人教版'],
    metadata: {
      subject: '数学',
      grade: '小学',
      standard: '人教版',
      region: '通用',
      format: 'PDF',
      size: '8.7 MB',
      pages: 56,
      uploadTime: '2026-03-31 16:20',
      uploader: '王芳',
      language: '中文',
      type: '练习册',
    },
    lineage: [
      { stage: '原始资料', label: 'PDF 文档', color: 'blue', status: 'completed', file: 'primary_math_app.pdf', size: '8.7 MB' },
      { stage: 'Rawcode', label: 'MinerU 输出', color: 'orange', status: 'completed', file: 'primary_math_app_raw.md', size: '1.6 MB' },
      { stage: 'Cleancode', label: 'AI清洗完成', color: 'green', status: 'completed', file: 'primary_math_app_clean.md', size: '1.2 MB' },
      { stage: '成品', label: '题库已生成', color: 'purple', status: 'completed', file: 'primary_math_bank.json', size: '900 KB' },
    ],
    history: [
      { id: 1, action: '生成成品题库', time: '1天前', operator: '系统', type: 'system', status: 'completed' },
      { id: 2, action: 'AI自动打标签', time: '1天前', operator: 'AI引擎', type: 'ai', status: 'completed' },
      { id: 3, action: '文件上传完成', time: '1天前', operator: '王芳', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.0', status: 'current', time: '2026-03-31 16:20', operator: '王芳', note: '初始上传版本' }],
    relatedAssets: [
      { id: 1, title: '2024年高考数学真题（全国卷I）', type: 'PDF', status: 'processing' },
      { id: 4, title: '高中物理实验指导手册', type: 'PPT', status: 'completed' },
      { id: 8, title: '小学语文阅读理解专项', type: 'PDF', status: 'reviewing' },
    ],
  },
  4: {
    id: 4,
    title: '高中物理实验指导手册',
    status: 'completed',
    assetId: 'AST-20240401-004',
    permission: 'review',
    tags: ['物理', '高中', '实验', '指导手册'],
    metadata: {
      subject: '物理',
      grade: '高中',
      standard: '新课标2022',
      region: '通用',
      format: 'PPT',
      size: '25.3 MB',
      pages: 42,
      uploadTime: '2026-03-31 15:50',
      uploader: '刘洋',
      language: '中文',
      type: '教学资料',
    },
    lineage: [
      { stage: '原始资料', label: 'PPT 课件', color: 'blue', status: 'completed', file: 'physics_lab_guide.ppt', size: '25.3 MB' },
      { stage: 'Rawcode', label: '结构抽取', color: 'orange', status: 'completed', file: 'physics_lab_raw.md', size: '2.0 MB' },
      { stage: 'Cleancode', label: 'AI清洗完成', color: 'green', status: 'completed', file: 'physics_lab_clean.md', size: '1.4 MB' },
      { stage: '成品', label: '讲义可用', color: 'purple', status: 'completed', file: 'physics_lab_notes.pdf', size: '3.1 MB' },
    ],
    history: [
      { id: 1, action: '讲义导出完成', time: '1天前', operator: '系统', type: 'system', status: 'completed' },
      { id: 2, action: '通过人工复核', time: '1天前', operator: '刘洋', type: 'user', status: 'completed' },
      { id: 3, action: '文件上传完成', time: '1天前', operator: '刘洋', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.1', status: 'current', time: '2026-03-31 15:50', operator: '刘洋', note: '修订实验步骤说明' }],
    relatedAssets: [
      { id: 3, title: '小学数学应用题集（人教版）', type: 'PDF', status: 'completed' },
      { id: 5, title: '初中历史知识点总结', type: 'PDF', status: 'pending' },
      { id: 7, title: '初中化学实验报告模板', type: 'DOCX', status: 'failed' },
    ],
  },
  5: {
    id: 5,
    title: '初中历史知识点总结',
    status: 'pending',
    assetId: 'AST-20240401-005',
    permission: 'internal',
    tags: ['历史', '初中', '知识点'],
    metadata: {
      subject: '历史',
      grade: '初中',
      standard: '义务教育课标',
      region: '通用',
      format: 'PDF',
      size: '5.1 MB',
      pages: 30,
      uploadTime: '2026-03-30 10:30',
      uploader: '陈刚',
      language: '中文',
      type: '教学资料',
    },
    lineage: [
      { stage: '原始资料', label: 'PDF 文档', color: 'blue', status: 'completed', file: 'history_points.pdf', size: '5.1 MB' },
      { stage: 'Rawcode', label: '待开始', color: 'orange', status: 'pending', file: null, size: null },
      { stage: 'Cleancode', label: '待生成', color: 'green', status: 'pending', file: null, size: null },
      { stage: '成品', label: '待生成', color: 'purple', status: 'pending', file: null, size: null },
    ],
    history: [
      { id: 1, action: '等待AI任务调度', time: '2天前', operator: '系统', type: 'system', status: 'pending' },
      { id: 2, action: '文件上传完成', time: '2天前', operator: '陈刚', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.0', status: 'current', time: '2026-03-30 10:30', operator: '陈刚', note: '初始上传版本' }],
    relatedAssets: [
      { id: 2, title: '初中英语语法专项练习', type: 'DOCX', status: 'completed' },
      { id: 6, title: '高考英语作文范文集', type: 'DOCX', status: 'completed' },
      { id: 8, title: '小学语文阅读理解专项', type: 'PDF', status: 'reviewing' },
    ],
  },
  6: {
    id: 6,
    title: '高考英语作文范文集',
    status: 'completed',
    assetId: 'AST-20240401-006',
    permission: 'production',
    tags: ['英语', '高三', '作文', '范文'],
    metadata: {
      subject: '英语',
      grade: '高三',
      standard: '新课标2022',
      region: '通用',
      format: 'DOCX',
      size: '1.8 MB',
      pages: 22,
      uploadTime: '2026-03-30 09:20',
      uploader: '赵敏',
      language: '中英混排',
      type: '教学资料',
    },
    lineage: [
      { stage: '原始资料', label: 'Word 文档', color: 'blue', status: 'completed', file: 'english_essay_samples.docx', size: '1.8 MB' },
      { stage: 'Rawcode', label: 'MinerU 输出', color: 'orange', status: 'completed', file: 'english_essay_raw.md', size: '420 KB' },
      { stage: 'Cleancode', label: 'AI清洗完成', color: 'green', status: 'completed', file: 'english_essay_clean.md', size: '390 KB' },
      { stage: '成品', label: '范文集已发布', color: 'purple', status: 'completed', file: 'english_essay_booklet.pdf', size: '1.1 MB' },
    ],
    history: [
      { id: 1, action: '资料发布', time: '2天前', operator: '赵敏', type: 'user', status: 'completed' },
      { id: 2, action: 'AI自动打标签', time: '2天前', operator: 'AI引擎', type: 'ai', status: 'completed' },
      { id: 3, action: '文件上传完成', time: '2天前', operator: '赵敏', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.2', status: 'current', time: '2026-03-30 09:20', operator: '赵敏', note: '补充 2024 热点话题范文' }],
    relatedAssets: [
      { id: 2, title: '初中英语语法专项练习', type: 'DOCX', status: 'completed' },
      { id: 1, title: '2024年高考数学真题（全国卷I）', type: 'PDF', status: 'processing' },
      { id: 5, title: '初中历史知识点总结', type: 'PDF', status: 'pending' },
    ],
  },
  7: {
    id: 7,
    title: '初中化学实验报告模板',
    status: 'failed',
    assetId: 'AST-20240401-007',
    permission: 'review',
    tags: ['化学', '初中', '实验'],
    metadata: {
      subject: '化学',
      grade: '初中',
      standard: '义务教育课标',
      region: '通用',
      format: 'DOCX',
      size: '2.4 MB',
      pages: 18,
      uploadTime: '2026-03-29 17:10',
      uploader: '孙磊',
      language: '中文',
      type: '教学资料',
    },
    lineage: [
      { stage: '原始资料', label: 'Word 模板', color: 'blue', status: 'completed', file: 'chemistry_lab_template.docx', size: '2.4 MB' },
      { stage: 'Rawcode', label: '解析失败', color: 'orange', status: 'failed', file: 'chemistry_lab_raw.md', size: '260 KB' },
      { stage: 'Cleancode', label: '中止', color: 'green', status: 'pending', file: null, size: null },
      { stage: '成品', label: '中止', color: 'purple', status: 'pending', file: null, size: null },
    ],
    history: [
      { id: 1, action: 'LaTeX解析失败', time: '3天前', operator: '系统', type: 'system', note: '第127行缺少闭合括号', status: 'failed' },
      { id: 2, action: '提交重试申请', time: '3天前', operator: '孙磊', type: 'user', status: 'reviewing' },
      { id: 3, action: '文件上传完成', time: '3天前', operator: '孙磊', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.0', status: 'current', time: '2026-03-29 17:10', operator: '孙磊', note: '初始上传版本' }],
    relatedAssets: [
      { id: 4, title: '高中物理实验指导手册', type: 'PPT', status: 'completed' },
      { id: 5, title: '初中历史知识点总结', type: 'PDF', status: 'pending' },
      { id: 8, title: '小学语文阅读理解专项', type: 'PDF', status: 'reviewing' },
    ],
  },
  8: {
    id: 8,
    title: '小学语文阅读理解专项',
    status: 'reviewing',
    assetId: 'AST-20240401-008',
    permission: 'review',
    tags: ['语文', '小学', '阅读理解'],
    metadata: {
      subject: '语文',
      grade: '小学',
      standard: '人教版',
      region: '通用',
      format: 'PDF',
      size: '6.9 MB',
      pages: 40,
      uploadTime: '2026-03-29 15:45',
      uploader: '周静',
      language: '中文',
      type: '练习册',
    },
    lineage: [
      { stage: '原始资料', label: 'PDF 文档', color: 'blue', status: 'completed', file: 'chinese_reading_primary.pdf', size: '6.9 MB' },
      { stage: 'Rawcode', label: 'MinerU 输出', color: 'orange', status: 'completed', file: 'chinese_reading_raw.md', size: '980 KB' },
      { stage: 'Cleancode', label: 'AI清洗完成', color: 'green', status: 'completed', file: 'chinese_reading_clean.md', size: '860 KB' },
      { stage: '成品', label: '待审核', color: 'purple', status: 'reviewing', file: 'chinese_reading_exam.pdf', size: '1.4 MB' },
    ],
    history: [
      { id: 1, action: '进入人工复核', time: '3天前', operator: '周静', type: 'user', status: 'reviewing' },
      { id: 2, action: 'AI自动打标签', time: '3天前', operator: 'AI引擎', type: 'ai', status: 'completed' },
      { id: 3, action: '文件上传完成', time: '3天前', operator: '周静', type: 'user', status: 'completed' },
    ],
    versions: [{ version: 'v1.0', status: 'current', time: '2026-03-29 15:45', operator: '周静', note: '初始上传版本' }],
    relatedAssets: [
      { id: 3, title: '小学数学应用题集（人教版）', type: 'PDF', status: 'completed' },
      { id: 5, title: '初中历史知识点总结', type: 'PDF', status: 'pending' },
      { id: 6, title: '高考英语作文范文集', type: 'DOCX', status: 'completed' },
    ],
  },
};
